spring:
  application:
    name: medical-api
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    spring:
      h2:
        console:
          enabled: true
  datasource:
    url: jdbc:h2:mem:medical
#    jdbc:h2:file:D:\database\saves;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
    enabled: true
  h2:
    console:
      enabled: true
jwt:
  secret:
    key: 0cO07vQyKtT/sBFSAOl7rIWAfaJah//ikKrbP0lLmLQ=
openai:
      model: gpt-3.5-turbo
      api:
        key: openaikey
        url: https://api.openai.com/v1/chat/completions

